### PR TITLE
This patch will reduce the TranslationImport command's running time from 45+ mins to 1.5 mins.

### PR DESCRIPTION
**Pull request by ynx**

### CODE REVIEW

**Comment by kinncj** [comment]
:+1:

**Comment by cabello** [comment]
Awesome job Shay. :+1:

**Comment by ynx** [comment]
Thanks! robocoder contributed to the final solution too. =D

**Comment by shiroyuki** [comment]
Bravo. :+1:

**Comment by eldar-ca** [comment]
:+1:

**Comment by davidmaignan** [comment]
Awesome

**Comment by okovalov** [comment]
amazing. thank you! :+1:

**Pull request merged**
