### PR TITLE
Fix some configuration bugs and add some info about the configuration in README.md

### PR DESCRIPTION
**Pull request by catacgc**

### CODE REVIEW

**Comment by guilhermeblanco** [comment]
Hi,

Inside of supports method, you can make it generic by comparing the method getFileExtension(). I used the same idea in exporters. Also, the XLIFF file extension is xliff and not xlf.
If you can make this change, I'm more than happy to accept you patch

**Comment by catacgc** [comment]
about the xliff to xlf renaming: in sf 2.1 xliff was renamed xlf - see commit https://github.com/symfony/symfony/commit/2cb6260 and sf 2.1 changelog: https://github.com/symfony/symfony/blob/master/CHANGELOG-2.1.md. Anyway, you are right and is better to be BC with sf 2.0

**Comment by shiroyuki** [comment]
@catacgc: I have no problem with `.xlf` but it would be nice if:
- In SF 2.0.x, the importer and exporter solely support `.xliff`.
- In SF 2.1.x, the importer can import either of them but uses `.xlf` before `.xliff`. The exporter only supports `.xlf`.

To detect the version (just in case you don't know), you can do by using `(string) \Symfony\Component\HttpKernel\Kernel::VERSION`.

**Comment by catacgc** [comment]
@shiroyuki Yeah, in the pull request I replaced the xlf check with xliff because otherwise the bundle will not be compatible with 2.0

**Pull request merged**
